// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-venues.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-venues.ts
var search_venues_default = defineTool({
  name: "search_venues",
  title: "Search venues",
  description: "Search Tampa Bay nightlife venues by name, location, or category.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match against venue name or location."),
    category: z.string().trim().optional().describe("Optional venue category filter."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of venues to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("venues").select("id, name, location, category, description, verified, is_active").eq("is_active", true).limit(limit ?? 10);
    if (query) request = request.or(`name.ilike.%${query}%,location.ilike.%${query}%`);
    if (category) request = request.eq("category", category);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-venue.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_venue_default = defineTool2({
  name: "get_venue",
  title: "Get venue details",
  description: "Fetch full details for one venue by its ID.",
  inputSchema: { venue_id: z2.string().uuid().describe("The venue's UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ venue_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("venues").select("id, name, location, category, description, image_url, verified, is_active, created_at").eq("id", venue_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Venue not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { venue: data }
    };
  }
});

// src/lib/mcp/tools/list-my-tickets.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_tickets_default = defineTool3({
  name: "list_my_tickets",
  title: "List my tickets",
  description: "List the signed-in user's tickets (wallet passes), optionally filtered by status.",
  inputSchema: {
    status: z3.enum(["active", "used", "refunded"]).optional().describe("Optional ticket status filter."),
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of tickets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("tickets").select("id, venue_id, status, price_paid, created_at, venues(name, location)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) request = request.eq("status", status);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Manolo profile: role, verification status, and bio.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, username, display_name, bio, role_type, sub_role, is_verified_talent, is_verified_manager").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/search-talent.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var search_talent_default = defineTool5({
  name: "search_talent",
  title: "Search talent",
  description: "Search verified talent profiles (DJs, performers, hosts) by name or sub-role.",
  inputSchema: {
    query: z4.string().trim().optional().describe("Text to match against display name or username."),
    sub_role: z4.string().trim().optional().describe("Optional talent sub-role filter, e.g. 'dj'."),
    limit: z4.number().int().min(1).max(50).default(10).describe("Maximum number of profiles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, sub_role, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("profiles").select("id, username, display_name, bio, sub_role, is_verified_talent").eq("role_type", "talent").limit(limit ?? 10);
    if (query) request = request.or(`display_name.ilike.%${query}%,username.ilike.%${query}%`);
    if (sub_role) request = request.eq("sub_role", sub_role);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { talent: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zfghkkhsdqsrjkbpkujn";
var mcp_default = defineMcp({
  name: "manolo-s-vibe-ai",
  title: "Manolo's Vibe AI",
  version: "0.1.0",
  instructions: "Tools for Manolo's Vibe AI, a Tampa Bay nightlife marketplace. Use `search_venues` and `get_venue` to browse venues, `search_talent` to find DJs and performers, `list_my_tickets` for the signed-in user's wallet passes, and `get_my_profile` for their account role and verification status. All tools act as the signed-in user under row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_venues_default, get_venue_default, search_talent_default, list_my_tickets_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
